/**
 * Style Dictionary v3 — Edore Design Token Build Config
 *
 * Input:  packages/tokens/src/*.json
 * Output:
 *   build/css/tokens.css   → Next.js import trong globals.css
 *   build/js/tokens.js     → JS/TS import trong component code
 *   build/js/tokens.d.ts   → TypeScript type definitions
 *   build/dart/tokens.dart → (placeholder) Flutter import
 *
 * Chạy: npm run build (trong packages/tokens)
 * Hoặc từ root: npm run tokens:build
 */

const StyleDictionary = require("style-dictionary");

// ─── Custom format: TypeScript declarations ───────────────────────────────────
StyleDictionary.registerFormat({
  name: "typescript/declarations",
  formatter: ({ dictionary }) => {
    const lines = dictionary.allProperties.map((token) => {
      const name = token.name
        .replace(/-([a-z])/g, (_, c) => c.toUpperCase()) // camelCase
        .replace(/^([a-z])/, (_, c) => c.toUpperCase()); // PascalCase first letter
      return `export declare const ${token.name}: ${JSON.stringify(token.value)};`;
    });
    return [
      "/**",
      " * @edore/tokens — Auto-generated TypeScript declarations",
      " * ⚠️  DO NOT EDIT — regenerate with: npm run tokens:build",
      " */",
      "",
      ...lines,
      "",
    ].join("\n");
  },
});

// ─── Custom format: Dart class (placeholder, đủ dùng cho Flutter sau này) ─────
StyleDictionary.registerFormat({
  name: "dart/class",
  formatter: ({ dictionary }) => {
    const fields = dictionary.allProperties.map((token) => {
      const name = token.name.replace(/-([a-z])/g, (_, c) => c.toUpperCase()); // camelCase
      const value = token.value;
      // Convert #rrggbb → Color(0xFF rrggbb) for color tokens
      const isColor = /^#[0-9a-fA-F]{6}$/.test(value);
      const dartValue = isColor
        ? `const Color(0xFF${value.slice(1).toUpperCase()})`
        : `'${value}'`;
      return `  static const ${name} = ${dartValue};`;
    });
    return [
      "// Auto-generated by Style Dictionary — DO NOT EDIT",
      "// Source: packages/tokens/src/*.json",
      "// Regenerate: npm run tokens:build (from monorepo root)",
      "",
      "import 'package:flutter/material.dart';",
      "",
      "/// Edore Design Tokens",
      "abstract class EdoreTokens {",
      ...fields,
      "}",
      "",
    ].join("\n");
  },
});

// ─── Build config ──────────────────────────────────────────────────────────────
module.exports = {
  source: ["src/**/*.json"],

  platforms: {
    // 1. CSS Custom Properties → apps/web import trực tiếp
    css: {
      transformGroup: "css",
      buildPath: "build/css/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: {
            outputReferences: true, // semantic token alias (e.g. var(--color-primary-500))
          },
        },
      ],
    },

    // 2. JavaScript module → dùng trong code TS/JS
    js: {
      transformGroup: "js",
      buildPath: "build/js/",
      files: [
        {
          destination: "tokens.js",
          format: "javascript/module-flat",
        },
        {
          destination: "tokens.d.ts",
          format: "typescript/declarations",
        },
      ],
    },

    // 3. Dart class → placeholder cho Flutter (tương lai)
    dart: {
      transformGroup: "css", // reuse css transform (name + value), dart format handles output
      buildPath: "build/dart/",
      files: [
        {
          destination: "tokens.dart",
          format: "dart/class",
        },
      ],
    },
  },
};
